name: Update Submodule Ref in Parent Repo

on:
  push:
    branches:
      - main

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    env:
      PARENT_REPO: kulupu-lapo/lipu
      PARENT_BRANCH: main
      SUBMODULE_PATH: poki

    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SUBMODULE_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone parent repository with submodules
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git clone --recurse-submodules git@github.com:${{ env.PARENT_REPO }} parent-repo
          cd parent-repo

      - name: Update submodule reference
        run: |
          cd parent-repo
          git submodule update --remote $SUBMODULE_PATH
          git add $SUBMODULE_PATH
          if git diff --cached --quiet; then
            echo "No submodule changes to commit"
            exit 0
          fi
          git commit -m "Update submodule to latest commit"
          git push origin $PARENT_BRANCH
